clc;
clearvars;
%STEPS TO COMPUTE THE MONTECARLO METHOD FOR BLACK AND SHALTZ
%WE OBTAIN THE V MATRIX THROUGH THE CALIBRATION
% we want to know if mark impl vol is the same as lv_impl_vol

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MARKET DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% market expiries; coincide with expiries of the LV matrix
T = [ 0.063 0.159 0.312 0.562 0.830 1.079 1.578 2.077];

% forwards at market expiries
Fwd = [3569.94 3563.83 3556.12 3473.93 3463.98 3446.99 3352.65 3329.88];

% discount factor at market expiry
DF = [1.0002428 1.0005586 1.0010088 1.0014682 1.0022950 1.0030480 1.0042523 1.0048028];

% market strikes
K = [
    3300	3050	2850	2500	2300	2150	1850	1700;
    3450	3450	3350	3150	3100	3000	2800	2750;
    3500	3500	3500	3350	3350	3300	3150	3100;
    3550	3550	3550	3450	3450	3450	3350	3350;
    3600	3600	3600	3550	3600	3600	3550	3550;
    3650	3650	3700	3700	3750	3800	3800	3850;
    3700	3800	3950	4000	4150	4250	4450	4650];

% market volatilities
MktVol = [
    0.1876	0.2321	0.2370	0.2639	0.2763	0.2778	0.2859	0.2852;
    0.1438	0.1389	0.1619	0.1841	0.1897	0.1974	0.2058	0.2046;
    0.1296	0.1280	0.1411	0.1620	0.1663	0.1740	0.1834	0.1860;
    0.1156	0.1173	0.1344	0.1512	0.1574	0.1630	0.1717	0.1742;
    0.1021	0.1072	0.1279	0.1410	0.1449	0.1529	0.1611	0.1659;
    0.0935	0.0991	0.1163	0.1282	0.1348	0.1414	0.1506	0.1560;
    0.0934	0.0930	0.1073	0.1119	0.1179	0.1243	0.1357	0.1416];


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CALIBRATION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% normalized market strikes
[rows, cols] = size(K);
K_norm = K ./ repmat(Fwd, rows, 1);

% Dupire solver settings
N = 10;
M = 200;
K_min = 0.1;
K_max = 3;
Scheme = 'cn';

% calibration settings
Threshold = 0.0010;
MaxIter = 100;

[V, ModelVol, MaxErr] = calibrator(T,K_norm,MktVol,Threshold,MaxIter,N,M,K_min,K_max,Scheme);
% calibration fction returns V

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PRICING
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% option data
expiry = 1.079;
strike = 3600;

N = 1000000; %MC simulations
M = 100; %timesteps

% MC simulation (Local Vol)
%M nmber of montec simulations= how many j's we use 
S = lv_simulation_log(T,Fwd,V,K,N,M,expiry); %returns phi(s(j's))

% LV price of a call option
discount_factor = interp1(T,DF,expiry); % = discount(T,r,expiry)
lv_price = discount_factor*mean(max(S(1,:) - strike,0));%this computes the mean mu hat
%%COMPUTE VN HAT IN THE LAB
% the 2 montecarlo models the Black one and the loc vol LV are differente and have diff distribution
%so they will have diff prices except for the call in the calibration
%to this very singular option all 2 models calibrated on one singe option
%so this price is the same
% LV implied volatility
fwd = interp1(T,Fwd,expiry); % = forward(T,r,q,expiry);
lv_impl_vol = blsimpv(fwd,strike,0,expiry,lv_price/discount_factor);


% MC simulation (Black) %SLIDE 124
time_idx = find(T>=expiry,1);
%we use mkt vol inside the black model we obtain the black price,same in
%montecarlo which as to be equal to the market price
sigma = interp1(K(:,time_idx),MktVol(:,time_idx),strike); % model parameter
N_B = 1000000; %MC simulations
S_B = black_simulation_log(T,Fwd,sigma,N_B,expiry); 

% Black price of a call option
price_black = discount_factor*mean(max(S_B(1,:) - strike,0));
black_impl_vol = blsimpv(fwd,strike,0,expiry,price_black/discount_factor);


% Probability densities generated by Monte Carlo simulation for LV and
% Black model
figure;
hist(S_B(1,:),100);
title('Probability density generated by Black model');

figure;
hist(S(1,:),100);
title('Probability density generated by LV model');
